### ISSUE TITLE
maxContainerExtent在滑动到一定程度之后，始终为固定值？

### ISSUE THREAD

**Issue by caihua** [fluttercandies/extended_nested_scroll_view#1]
maxContainerExtent = math.max(
        notification.metrics.viewportDimension, this.maxContainerExtent);
maxContainerExtent在滑动到一定程度之后，始终为固定值，
上拉加载如何实现，或者想在外部，body里面通过Controller 操作 _innerController进行jumpTo等操作如何实现，
有什么好的思路吗？

**Comment by zmtzawqlp** [comment]
@caihua https://juejin.im/post/5bfb9cb7e51d45592b766769 
上拉加载的完美方案，跟nestedscrollview完美结合，已使用在上线项目中。

**Comment by zmtzawqlp** [comment]
@caihua 里面也有demo https://github.com/fluttercandies/loading_more_list/blob/master/example/lib/demo/nested_scroll_view_demo.dart
