### ISSUE TITLE
I got this issue when upgrade flutter to 1.7 stable version. thanks 

### ISSUE THREAD

**Issue by dwikresno** [fluttercandies/extended_nested_scroll_view#10]
Compiler message:
file:///E:/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/extended_nested_scroll_view-0.3.5/lib/src/nested_scroll_view_refresh_indicator.dart:363:24: Error: The argument type 'String' can't be assigned to the parameter type 'DiagnosticsNode'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///E:/Flutter/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'DiagnosticsNode'.
              context: 'when calling onRefresh',
                       ^
Compiler failed on E:\Flutter_projects\Lari.id.flutter - Copy (2)\lib/main.dart

FAILURE: Build failed with an exception.

**Comment by zmtzawqlp** [comment]
```dart
  extended_nested_scroll_view:
    git:
      url: https://github.com/fluttercandies/extended_nested_scroll_view.git
      ref: dev
```
link it as this,  i will update codes to pub later

**Comment by dwikresno** [comment]
that work perfectly, thank you so much, i'll wait for pub
