### ISSUE TITLE
当设置顶部view的高度特别高的时候，向上滑动菜单会出现 显示不全的错误

### ISSUE THREAD

**Issue by kangshibiao123** [fluttercandies/extended_nested_scroll_view#106]
尝试一下两个版本都试了，当设置顶部view的高度特别高的时候，向上滑动菜单会出现 显示不全的错误
extended_nested_scroll_view: ^5.1.0
  extended_nested_scroll_view: ^4.0.0

      SliverToBoxAdapter(
                child: Container(
                  color: Colors.red,
                  alignment: Alignment.center,
                  height: 800,
                  child: const Text('other things'),
                ),
              ),

<img width="357" alt="image" src="https://user-images.githubusercontent.com/15258113/168266563-2efdfcd3-b438-483f-8e2a-3ca0fddeb2e3.png">

**Comment by zmtzawqlp** [comment]
不影响。release 不会出现。
