### ISSUE TITLE
Bump visibility_detector dependency version

### ISSUE THREAD

**Issue by adigladi** [fluttercandies/extended_nested_scroll_view#107]
Hi! Currently we're getting several warnings due to this package not using the latest `visibility_detector` version which has upgraded their linting for flutter v3.

Example of warning:
```
./../../.pub-cache/hosted/pub.dartlang.org/visibility_detector-0.2.2/lib/src/visibility_detector_layer.dart:126:28: Warning: Operand of null-aware operation '?.' has type 'RendererBinding' which excludes null.
```
Is it possible to bump this dependency version? I'm open for putting up a PR if needed!

**Comment by zmtzawqlp** [comment]
dependency_overrides:
visibility_detector: ^0.3.3

**Comment by adigladi** [comment]
Okay, thanks!

Could an option be to use LTS releases for supporting older versions, similar to how it's done here maybe?
https://github.com/tanersener/ffmpeg-kit#10-lts-releases

**Comment by zmtzawqlp** [comment]
if you are in flutter 3.0.0, the version of visibility_detector will be 0.3.3 automatically

**Comment by adigladi** [comment]
I'm on 3.0.1 and I need to set an explicit override to get version 0.3.3.

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_nested_scroll_view/commit/029b0911cf3cfea57e8277e8a63429b26dc18aba
