### ISSUE TITLE
列表滚动同步，好像不行了

### ISSUE THREAD

**Issue by YQjiuhao** [fluttercandies/extended_nested_scroll_view#11]
Flutter:1.7.8+hotfix.3 
extended_nexsted_scroll_view 0.3.6
使用TabBar与PageView搭配使用，放PageView存放GridView,已经使用NestedScrollViewInnerScrollPositionKeyWidget和给定不同的key

**Comment by zmtzawqlp** [comment]
pageview放gridview是什么操作。。。( ╯□╰ )

**Comment by YQjiuhao** [comment]
神操作啊，之前可以的，现在必须要实现innerScrollPositionKeyBuilder

**Comment by zmtzawqlp** [comment]
一直都是这样的哦
