### ISSUE TITLE
设置过ExtendedVisibilityDetector uniqueKey 后 控制台一直打印 is visible

### ISSUE THREAD

**Issue by muchenfine** [fluttercandies/extended_nested_scroll_view#113]
I/flutter ( 2809): [<'AIssue2'>] is visible
2
I/flutter ( 2809): [<'ASpotCheck1'>] is visible
3
I/flutter ( 2809): [<uction0'>] is visible
2
I/flutter ( 2809): [<e2'>] is visible
2
I/flutter ( 2809): [<'duction0'>] is visible
2
I/flutter ( 2809): [<'sue2'>] is visible
2
I/flutter ( 2809): [<'oduction0'>] is visible
2
I/flutter ( 2809): [<'heck1'>] is visible
32
I/flutter ( 2809): [<'Issue2'>] is visible

**Comment by muchenfine** [comment]
有时候会打印600多次。
![图片](https://user-images.githubusercontent.com/94693483/183572586-6cf6a74a-a85c-415e-8841-f13da165f02e.png)

**Comment by muchenfine** [comment]
![图片](https://user-images.githubusercontent.com/94693483/183573233-602985fe-3317-437e-b1e7-f5894544c2de.png)
下拉刷新是会持续打印600多次

**Comment by zmtzawqlp** [comment]
正常的。你可以了解下 VisibilityDetector

**Comment by muchenfine** [comment]
@zmtzawqlp  

按照官网的例子，refresh和extended_nested_scroll_view一起使用时，滚动就会出现这个错误

RenderBox.size accessed beyond the scope of resize, layout, or permitted parent access. RenderBox can always access its own size, otherwise, the only object that is allowed to read RenderBox.size is its parent, if they have said they will. It you hit this assert trying to access a child's size, pass "parentUsesSize: true" to that child's layout().
'package:flutter/src/rendering/box.dart':
package:flutter/…/rendering/box.dart:1
Failed assertion: line 1987 pos 13: 'debugDoingThisResize || debugDoingThisLayout || _computingThisDryLayout ||
              (RenderObject.debugActiveLayout == parent && size._canBeUsedByParent)'

**Comment by zmtzawqlp** [comment]
官方demo 能重现吗？ 步骤是啥

**Comment by Livjxbill993** [comment]
> 正常的。你可以了解下 VisibilityDetector

法老，可以关闭控制台这样的输出吗，这个只有在debug模式下才会有吗

**Comment by zmtzawqlp** [comment]
> > 正常的。你可以了解下 VisibilityDetector
> 
> 法老，可以关闭控制台这样的输出吗，这个只有在debug模式下才会有吗

嗯 ，debug 下面才会打印 https://github.com/fluttercandies/extended_nested_scroll_view/blob/029b0911cf3cfea57e8277e8a63429b26dc18aba/lib/src/extended_nested_scroll_view_part.dart#L91

**Comment by Junesui** [comment]
> @zmtzawqlp
> 
> 按照官网的例子，refresh和extended_nested_scroll_view一起使用时，滚动就会出现这个错误
> 
> RenderBox.size accessed beyond the scope of resize, layout, or permitted parent access. RenderBox can always access its own size, otherwise, the only object that is allowed to read RenderBox.size is its parent, if they have said they will. It you hit this assert trying to access a child's size, pass "parentUsesSize: true" to that child's layout(). 'package:flutter/src/rendering/box.dart': package:flutter/…/rendering/box.dart:1 Failed assertion: line 1987 pos 13: 'debugDoingThisResize || debugDoingThisLayout || _computingThisDryLayout || (RenderObject.debugActiveLayout == parent && size._canBeUsedByParent)'

你好。这个问题解决了吗？
listview 数据变化的时候控制台会报上面这个错误。如果数据不变化一直刷新是没有报错的
