### ISSUE TITLE
滚动时报错

### ISSUE THREAD

**Issue by muchenfine** [fluttercandies/extended_nested_scroll_view#114]
════════ Exception caught by animation library ═════════════════════════════════
The following assertion was thrown while notifying listeners for AnimationController:
'package:extended_nested_scroll_view/src/extended_nested_scroll_view.dart': Failed assertion: line 1760 pos 9: 'result': is not true.
package:extended_nested_scroll_view/src/extended_nested_scroll_view.dart:1760

When the exception was thrown, this was the stack
#2      _NestedOuterBallisticScrollActivity.applyMoveTo
package:extended_nested_scroll_view/src/extended_nested_scroll_view.dart:1760
#3      BallisticScrollActivity._tick
package:flutter/…/widgets/scroll_activity.dart:553
#4      AnimationLocalListenersMixin.notifyListeners
package:flutter/…/animation/listener_helpers.dart:155
#5      AnimationController._tick
package:flutter/…/animation/animation_controller.dart:830
#6      Ticker._tick
package:flutter/…/scheduler/ticker.dart:238
#7      SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1146
#8      SchedulerBinding.handleBeginFrame.<anonymous closure>
package:flutter/…/scheduler/binding.dart:1059

**Comment by muchenfine** [comment]
════════ Exception caught by animation library ═════════════════════════════════
The following assertion was thrown while notifying listeners for AnimationController:
'package:extended_nested_scroll_view/src/extended_nested_scroll_view.dart': Failed assertion: line 1760 pos 9: 'result': is not true.
package:extended_nested_scroll_view/src/extended_nested_scroll_view.dart:1760

When the exception was thrown, this was the stack
#2      _NestedOuterBallisticScrollActivity.applyMoveTo
package:extended_nested_scroll_view/src/extended_nested_scroll_view.dart:1760
#3      BallisticScrollActivity._tick
package:flutter/…/widgets/scroll_activity.dart:553
#4      AnimationLocalListenersMixin.notifyListeners
package:flutter/…/animation/listener_helpers.dart:155
#5      AnimationController._tick
package:flutter/…/animation/animation_controller.dart:830
#6      Ticker._tick
package:flutter/…/scheduler/ticker.dart:238
#7      SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1146
#8      SchedulerBinding.handleBeginFrame.<anonymous closure>
package:flutter/…/scheduler/binding.dart:1059

**Comment by zmtzawqlp** [comment]
demo，步骤

**Comment by chenfasheng** [comment]
> demo，步骤
这个问题我也出现了，经过多次测试，问题出在ExtendedNestedScrollView上。
前提条件：嵌套滚动布局的情况下
结果一：NestedScrollView（正常）
结果二：ExtendedNestedScrollView（提示）
