### ISSUE TITLE
flutter master分支的BallisticScrollActivity类需要4个参数了,直接编译不过

### ISSUE THREAD

**Issue by caihua** [fluttercandies/extended_nested_scroll_view#115]
extended_nested_scroll_view-5.1.3/lib/src/extended_nested_scroll_view.dart:1607:39: Error: Too few positional arguments: 4 required, 3 given.
return BallisticScrollActivity(this, simulation, context.vsync);

class BallisticScrollActivity extends ScrollActivity {
  /// Creates an activity that animates a scroll view based on a [simulation].
  ///
  /// The [delegate], [simulation], and [vsync] arguments must not be null.
  BallisticScrollActivity(
    super.delegate,
    Simulation simulation,
    TickerProvider vsync,
    this.shouldIgnorePointer,
  ) {
    _controller = AnimationController.unbounded(
      debugLabel: kDebugMode ? objectRuntimeType(this, 'BallisticScrollActivity') : null,
      vsync: vsync,
    )
      ..addListener(_tick)
      ..animateWith(simulation)
       .whenComplete(_end); // won't trigger if we dispose _controller first
  }

**Comment by zmtzawqlp** [comment]
稍后

**Comment by zmtzawqlp** [comment]
> 要修改下么，Flutter stable 3.3.3 也同步代码了

并没有发现有同步

**Comment by 1mavic** [comment]
> 感谢回复，查了下确实如此，是我本地缓存代码不太对

Hello, how you resolved this issue?

Tried to clear pub cache, didn't help.

**Comment by 1mavic** [comment]
> flutter channel stable

Thanks!
Problems was with VSCode and fvm. IDE didn't use local version of flutter.

**Comment by NatanielRegula** [comment]
@zmtzawqlp Hi, that breaking change was now merged into flutter stable branch causing the above mentioned error.
