### ISSUE TITLE
headerSliver高度超过半屏后，下拉会触发overscroll

### ISSUE THREAD

**Issue by zhao0** [fluttercandies/extended_nested_scroll_view#116]
视频demo中，手指在屏幕上半部分缓慢下拉时，触发了overscroll

https://user-images.githubusercontent.com/7556666/195525206-378ce1da-8719-4c41-85ba-a3771072f197.mp4

环境
Flutter 版本2.10.5
Android设备，iOS没问题

尝试把 https://github.com/fluttercandies/extended_nested_scroll_view/blob/master/lib/src/extended_nested_scroll_view.dart#L1300
```remainingDelta > 0.0```
改成
```remainingDelta > precisionErrorTolerance```，问题不再出现了，不知是否是这里的问题

[demo.zip](https://github.com/fluttercandies/extended_nested_scroll_view/files/9771576/flutter_easy_refresh-3.zip)

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_nested_scroll_view/blob/029b0911cf3cfea57e8277e8a63429b26dc18aba/lib/src/extended_nested_scroll_view_part.dart#L332

是的，这个一直都有精度问题，但是我也不能把全部的都改掉。

**Comment by zmtzawqlp** [comment]
建议你先给官方提issue
