### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by qidianli** [fluttercandies/extended_nested_scroll_view#118]
/C:/Users/zwhl/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/extended_nested_scroll_view-5.1.3/lib/src/extended_nested_scroll_view.dart:1398:7: Error: The non-abstract class '_NestedScrollPosition' is missing implementations for these members:
 - ScrollActivityDelegate.updateBallisticAnimation
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class _NestedScrollPosition extends ScrollPosition
      ^^^^^^^^^^^^^^^^^^^^^
/D:/Program%20Files/flutter_windows_2.9.0-0.1.pre-dev/flutter/packages/flutter/lib/src/widgets/scroll_activity.dart:59:15: Context: 'ScrollActivityDelegate.updateBallisticAnimation' is defined here.
  Simulation? updateBallisticAnimation(double initVelocity, double initPosition);

**Comment by zmtzawqlp** [comment]
please use latest flutter version and this package version
