### ISSUE TITLE
跟这个库marquee 冲突了

### ISSUE THREAD

**Issue by gyyxiaogao** [fluttercandies/extended_nested_scroll_view#119]
<img width="419" alt="image" src="https://user-images.githubusercontent.com/16957066/203247762-26f0e119-f88b-4d8c-a41f-8e88ae181084.png">
跑马灯在滚动的话无法下拉刷新

**Comment by zmtzawqlp** [comment]
建议查查google，是不是 marquee 把下拉的手势吃了？

**Comment by gyyxiaogao** [comment]
<img width="662" alt="image" src="https://user-images.githubusercontent.com/16957066/215934307-0ec10dd4-8f15-4bb2-846d-bb7d33b5d503.png">
需要等到这行代码执行完,下拉才会有反应

**Comment by zmtzawqlp** [comment]
看看 这个 https://juejin.cn/post/7012269905516953637#heading-7
