### ISSUE TITLE
怎么用easyrefresh嵌套extended_nested_scroll_view实现下拉刷新

### ISSUE THREAD

**Issue by charmfocus** [fluttercandies/extended_nested_scroll_view#12]
extended_nested_scroll_view提供的下拉刷新样式太单一，我怎么用easyrefresh来实现下拉刷新呢

**Comment by zmtzawqlp** [comment]
https://juejin.im/post/5bebcc44f265da61682aedb8   你可以试试这个下拉刷新，或者找easyrefresh 来支持

**Comment by fashare2015** [comment]
@charmfocus easyrefresh 支持这个，看它的demo。 https://github.com/xuelongqy/flutter_easyrefresh/blob/v2/example/lib/page/sample/nested_scroll_view.dart
