### ISSUE TITLE
升级最新版的flutter出现以下问题

### ISSUE THREAD

**Issue by heizimeng** [fluttercandies/extended_nested_scroll_view#122]
环境
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 3.8.0-7.0.pre.12, on Microsoft Windows [版本 10.0.19044.2364], locale zh-CN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Professional 2022 17.3.6)
[√] Android Studio (version 2021.3)
[√] Connected device (3 available)
[√] HTTP Host Availability
问题
Error: The method '_NestedScrollMetrics.copyWith' doesn't have the named parameter 'devicePixelRatio' of overridden method 'Object with ScrollMetrics.copyWith'.

**Comment by zmtzawqlp** [comment]
只维护最新的 stable 分支，master 的改动一日一变，还会有回退

**Comment by heizimeng** [comment]
好的，感谢回复，辛苦了！------------------------------------------------------------------
***@***.***>
日　期：2023年02月08日 13:10:27
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [fluttercandies/extended_nested_scroll_view] 升级最新版的flutter出现以下问题 (Issue #122)

只维护最新的 stable 分支，master 的改动一日一变，还会有回退

**Comment by heizimeng** [comment]
ok
