### ISSUE TITLE
[Bug report]  Please do not remove backward compatibility

### ISSUE THREAD

**Issue by gizemgizg** [fluttercandies/extended_nested_scroll_view#123]
### Version

6.0.0

### Platforms

dart, Android, iOS

### Device Model

iphone 14

### flutter info

```sh
My flutter version is 3.3.9 and I can't get a build because you made the flutter sdk minimum 3.7.0. Please do not remove backward compatibility. My project cannot switch to 3.7.0 at the moment. Can you fix it please.
```

### How to reproduce?

My flutter version is 3.3.9 and I can't get a build because you made the flutter sdk minimum 3.7.0. Please do not remove backward compatibility. My project cannot switch to 3.7.0 at the moment. Can you fix it please.

### Logs

```sh
pub get failed (1; Because xxx_app depends on extended_nested_scroll_view >=6.0.0 which requires Flutter SDK version >=3.7.0, version solving failed.)
```

### Contact

https://www.linkedin.com/in/gizemmalcok/

**Comment by zmtzawqlp** [comment]
check change log, and choice the version fit for your flutter sdk

**Comment by gizemgizg** [comment]
Sorry. When I delete the cache and do pub get again, the ^ at the beginning of the package version got the highest version because of this. Thank you for your answer. 💙
