### ISSUE TITLE
[Bug report] 

### ISSUE THREAD

**Issue by demoYang** [fluttercandies/extended_nested_scroll_view#143]
### Version

5.1.2

### Platforms

Android, iOS

### Device Model

iPhone13,2

### flutter info

```sh
[✓] Flutter (Channel stable, 3.3.7, on macOS 13.2.1 22D68 darwin-arm, locale zh-Hans-CN)
    • Flutter version 3.3.7 on channel stable at /Users/xuyang/fvm/versions/3.3.7
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (10 months ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc2)
    • Android SDK at /Users/xuyang/Library/Android/sdk
    • Platform android-33, build-tools 34.0.0-rc2
    • ANDROID_HOME = /Users/xuyang/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • V2133A (mobile) • 3030390513001O1 • android-arm64 • Android 11 (API 30)
    • macOS (desktop) • macos           • darwin-arm64  • macOS 13.2.1 22D68 darwin-arm

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

### How to reproduce?

线上问题, 没有复现;

是不是被释放了?

![image](https://github.com/fluttercandies/extended_nested_scroll_view/assets/7134823/c7ce7764-4201-434e-91ea-1419686c0da5)

**Comment by hylsabella** [comment]
> ### Version
> 5.1.2
> 
> ### Platforms
> Android, iOS
> 
> ### Device Model
> iPhone13,2
> 
> ### flutter info
> ```shell
> [✓] Flutter (Channel stable, 3.3.7, on macOS 13.2.1 22D68 darwin-arm, locale zh-Hans-CN)
>     • Flutter version 3.3.7 on channel stable at /Users/xuyang/fvm/versions/3.3.7
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision e99c9c7cd9 (10 months ago), 2022-11-01 16:59:00 -0700
>     • Engine revision 857bd6b74c
>     • Dart version 2.18.4
>     • DevTools version 2.15.0
>     • Pub download mirror https://pub.flutter-io.cn
>     • Flutter download mirror https://storage.flutter-io.cn
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc2)
>     • Android SDK at /Users/xuyang/Library/Android/sdk
>     • Platform android-33, build-tools 34.0.0-rc2
>     • ANDROID_HOME = /Users/xuyang/Library/Android/sdk
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 14.2)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Build 14C18
>     • CocoaPods version 1.11.3
> 
> [✓] Android Studio (version 2021.2)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
> 
> [✓] VS Code (version 1.81.1)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension can be installed from:
>       🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
> 
> [✓] Connected device (2 available)
>     • V2133A (mobile) • 3030390513001O1 • android-arm64 • Android 11 (API 30)
>     • macOS (desktop) • macos           • darwin-arm64  • macOS 13.2.1 22D68 darwin-arm
> 
> [✓] HTTP Host Availability
>     • All required HTTP hosts are available
> 
> • No issues found!
> ```
> 
> ### How to reproduce?
> 线上问题, 没有复现;
> 
> 是不是被释放了?
> 
> ![image](https://user-images.githubusercontent.com/7134823/263153030-c7ce7764-4201-434e-91ea-1419686c0da5.png)
> 
> ### Logs
> _No response_
> 
> ### Example code (optional)
> _No response_
> 
> ### Contact
> _No response_

都不知道你要问什么问题
