### ISSUE TITLE
ExtendedNestedScrollView 设置 NeverScrollableScrollPhysics 属性无效

### ISSUE THREAD

**Issue by czeras** [fluttercandies/extended_nested_scroll_view#144]
### Platforms

dart, iOS

### Description

在 ExtendedNestedScrollView 中设置 NeverScrollableScrollPhysics 属性无效，无法禁止滚动

### My code

  Widget _buildScaffoldBody() {
    final double statusBarHeight = MediaQuery.of(context).padding.top;
    final double pinnedHeaderHeight =
        //statusBar height
        statusBarHeight +
            //pinned SliverAppBar height in header
            kToolbarHeight;
    return ExtendedNestedScrollView(
      physics: NeverScrollableScrollPhysics(),
      headerSliverBuilder: (BuildContext c, bool f) {
        return buildSliverHeader();
      },
      //1.[pinned sliver header issue](https://github.com/flutter/flutter/issues/22393)
      pinnedHeaderSliverHeightBuilder: () {
        return pinnedHeaderHeight;
      },
      //2.[inner scrollables in tabview sync issue](https://github.com/flutter/flutter/issues/21868)
      onlyOneScrollInBody: true,
      body: Column(
        children: <Widget>[
          TabBar(
            controller: primaryTC,
            labelColor: Colors.blue,
            indicatorColor: Colors.blue,
            indicatorSize: TabBarIndicatorSize.label,
            indicatorWeight: 2.0,
            isScrollable: false,
            unselectedLabelColor: Colors.grey,
            tabs: const <Tab>[Tab(text: 'Tab1')],
          ),
          Expanded(
            child: TabBarView(
              physics: NeverScrollableScrollPhysics(),
              controller: primaryTC,
              children: <Widget>[
                // SecondaryTabView('Tab0', secondaryTC),
                ListView.builder(
                  key: const PageStorageKey<String>('Tab1'),
                  physics: const NeverScrollableScrollPhysics(),
                  itemCount: 50,
                  itemBuilder: (BuildContext c, int i) {
                    return Container(
                      alignment: Alignment.center,
                      height: 60.0,
                      child: Text(
                        const Key('Tab1').toString() + ': ListView$i',
                      ),
                    );
                  },
                ),
              ],
            ),
          )
        ],
      ),
    );
  }

### Try do it

![截屏2023-08-25 16 16 54](https://github.com/fluttercandies/extended_nested_scroll_view/assets/35266402/c0586e85-7472-4e15-8b1e-ab1d041b4795)

**Comment by zmtzawqlp** [comment]
先给官方开issue

**Comment by czeras** [comment]
好吧，那没问题了，给产品沟通修改交互方式
