### ISSUE TITLE
[Bug report] 

### ISSUE THREAD

**Issue by devyu** [fluttercandies/extended_nested_scroll_view#148]
### Version

5.1.3

### Platforms

iOS

### Device Model

iPhone X

### flutter info

```sh
physics设置为NeverScrollableScrollPhysics(),似乎无法禁止滚动？请教下有什么好的解决方案吗？
```

**Comment by devyu** [comment]
![image](https://github.com/fluttercandies/extended_nested_scroll_view/assets/15952780/4faa39c8-4cf1-405f-b495-dac18b0599ae)

**Comment by zmtzawqlp** [comment]
官方已只 issue吧。你先追踪下 flutter team

**Comment by devyu** [comment]
> 官方已只 issue吧。你先追踪下 flutter team

你好，当只有一个tab的时候，并不会有问题，当有两个以上的tab，禁用滑动就失效了

**Comment by zmtzawqlp** [comment]
merge code from https://github.com/flutter/flutter/pull/123109
