### ISSUE TITLE
[Bug report] 

### ISSUE THREAD

**Issue by jayrao5566** [fluttercandies/extended_nested_scroll_view#149]
### Version

6.2.0

### Platforms

dart, iOS

### Device Model

模拟器，ios17.2

### flutter info

```sh
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.5, on macOS 13.6.1 22G313 darwin-arm64 (Rosetta), locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Community Edition (version 2023.3)
[✓] IntelliJ IDEA Community Edition (version 2023.3)
[✓] VS Code (version 1.85.1)
```

### How to reproduce?

════════ Exception caught by rendering library ═════════════════════════════════
'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 616 pos 12: 'haveDimensions == (_lastMetrics != null)': is not true.
The relevant error-causing widget was:

════════ Exception caught by rendering library ═════════════════════════════════
'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 616 pos 12: 'haveDimensions == (_lastMetrics != null)': is not true.
The relevant error-causing widget was:

**Comment by sed1ka** [comment]
This happened to me too, with widget Structure

ExtendedNestedScrollView
   body: SingleChildScrolLView

**Comment by sed1ka** [comment]
I've tried to downgrade to extended_nested_scroll_view 3.1.2, calling flutter clean and flutter pub cache clean then pub get and trying on the flutter version 3.16.4 and 3.16.5 the error still persists. Even though it previously worked fine.

**Comment by hayderGo** [comment]
ios（17.1.2）和 vivo （android 13）真机也遇到了此问题。
组件初始化后会报
'package:extended_nested_scroll_view/src/extended_nested_scroll_view.dart': Failed assertion: line 1645 pos 12: 'coordinator._outerPosition == this': is not true.
滚动后会报
'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 616 pos 12: 'haveDimensions == (_lastMetrics != null)': is not true.

**Comment by chenfasheng** [comment]
同样遇到这种情况，用官方的NestedScrollView 则不会。
似乎不能正确嵌套滚动布局

**Comment by GuoguoDad** [comment]
回退吧，6.1.2是没这个问题的

**Comment by chenfasheng** [comment]
> 回退吧，6.1.2是没这个问题的

我的就是6.1.2，也是这个问题。

**Comment by GuoguoDad** [comment]
> > 回退吧，6.1.2是没这个问题的
> 
> 我的就是6.1.2，也是这个问题。
今天升级了6.2.0才出现，回退6.1.2就好了，不知道你这啥情况

**Comment by chinghoi** [comment]
我的6.1.2 没问题, 升级到6.2.0就有这个问题。

**Comment by zmtzawqlp** [comment]
暂时用 6.1.2 空了我看下

**Comment by zmtzawqlp** [comment]
assert 在这个场景下非必要

**Comment by zmtzawqlp** [comment]
请更新到 6.2.1
