### ISSUE TITLE
[How to use] 其中一个Tab下拉到顶部后，另一个Tab的数据还是会受影响

### ISSUE THREAD

**Issue by xuyisheng** [fluttercandies/extended_nested_scroll_view#153]
### Platforms

dart

### Description

RT，先看录屏

https://github.com/fluttercandies/extended_nested_scroll_view/assets/7419202/547306b6-27bf-4d7d-9acc-ed08e8c6fa79

第一个tab在index 10，第二个tab下拉滑动到顶部后，第一个tab的数据也变成index 0了。

### My code

用的Example中的Simple demos - pinned header

**Comment by zmtzawqlp** [comment]
拉到顶部了。是这样的。全部都会重置。这是代码就这样设计的。官方

**Comment by xuyisheng** [comment]
> 拉到顶部了。是这样的。全部都会重置。这是代码就这样设计的。官方

有规避方法吗？

**Comment by zmtzawqlp** [comment]
https://github.com/flutter/flutter/issues/40740#issuecomment-2062796061  你可以看看这个回复
