### ISSUE TITLE
当onlyOneScrollInBody设置为true的时候，如何获取到所有的innerController呢？

### ISSUE THREAD

**Issue by gdmec07120836** [fluttercandies/extended_nested_scroll_view#157]
### Platforms

Android, iOS

### Description

页面使用的是tabview，结构和example/lib/pages/complex/scroll_to_top.dart差不多，但如果像例子那样不设置onlyOneScrollInBody: true,会导致各个tab的刷新状态互相影响，如果设置onlyOneScrollInBody: true,则会导致scrollViewKey.currentState?.innerPosition获取出来的innerController只有当前页的，这种情况需要怎么处理呢？

**Comment by zmtzawqlp** [comment]
需求是什么，看看合理不，可以完全加一个public 的暴露呢？

**Comment by gdmec07120836** [comment]
不需要了，还是要用onlyOneScrollInBody: true的方式，因为false的时候各个tab的innerController会互相影响。不过我发现还有一个问题，就是和ExtendedTabBarView的兼容性不太好，我另外提个issues吧，这个可以关了。
