### ISSUE TITLE
Demo中ScrollToTop页面列表和Tabbar直接有一段空白，应该如何去掉？

### ISSUE THREAD

**Issue by lawlietwind** [fluttercandies/extended_nested_scroll_view#18]
出现步骤：![image](https://user-images.githubusercontent.com/13810063/68724374-3eaf7000-05f6-11ea-80c4-55be36b5c5dc.png)
系统信息：
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.15.1 19B88, locale en-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.39.2)
[✓] Connected device (1 available)

• No issues found!

版本号：0.3.8
补充说明：使用普通的ListView或者LoadMoreList不会出现问题，自己封装了一个加载更多的组件会出现列表顶部的空白，检查页面没有发现添加了Padding，应该是中间多了一个组件，烦请看看如何解决？

**Comment by zmtzawqlp** [comment]
没法云debug

**Comment by lawlietwind** [comment]
example例子中ScrollToTop页面列表就有这个问题

> 没法云debug

**Comment by zmtzawqlp** [comment]
ListView有默认padding
