### ISSUE TITLE
_NestedScrollController: activeCount is 0, please report to zmtzawqlp@live.com and show your case

### ISSUE THREAD

**Issue by qq329401134** [fluttercandies/extended_nested_scroll_view#2]
![image](https://user-images.githubusercontent.com/38587734/55124279-b05aac80-5140-11e9-8b03-7c87ec476ccf.png)
当我把红框的控件加上flutter_easyrefresh的时候，当切换到第二个tab的时候会出现，不太懂为什么
_NestedScrollController: activeCount is 0, please report to zmtzawqlp@live.com and show your case.

**Comment by qq329401134** [comment]
但是使用NestedScrollViewRefreshIndicator包裹的时候就不会出现以上问题，希望可以指教一下

**Comment by zmtzawqlp** [comment]
建议使用old的那个。new的在某些特殊场景会不准确

**Comment by qq329401134** [comment]
好了  完美  谢谢
