### ISSUE TITLE
example 跑不起来

### ISSUE THREAD

**Issue by wanghuiwen1** [fluttercandies/extended_nested_scroll_view#25]
scroll_to_top.dart 文件里的21行 NestedScrollViewState无法导入
![image](https://user-images.githubusercontent.com/20026925/75939458-3a6cd280-5ec5-11ea-93f2-47eeefae4bf3.png)
![image](https://user-images.githubusercontent.com/20026925/75939491-54a6b080-5ec5-11ea-9c75-cdfc978293c1.png)

**Comment by zmtzawqlp** [comment]
你是高版本的sdk吧。。 把官方的NestedScrollViewState hide掉

**Comment by wanghuiwen1** [comment]
好的谢谢



发自我的小米手机在 zmtzawqlp <notifications@github.com>，2020年3月5日 下午1:41写道：你是高版本的sdk吧。。 把官方的NestedScrollViewState hide掉



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/fluttercandies/extended_nested_scroll_view/issues/25?email_source=notifications\u0026email_token=AEYZMLKAF5OLDTOK45KJBRTRF43QHA5CNFSM4LB7XRD2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEN3ZHCI#issuecomment-595039113",

"url": "https://github.com/fluttercandies/extended_nested_scroll_view/issues/25?email_source=notifications\u0026email_token=AEYZMLKAF5OLDTOK45KJBRTRF43QHA5CNFSM4LB7XRD2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEN3ZHCI#issuecomment-595039113",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
