### ISSUE TITLE
NestedScrollView 滚动列表在某些机型上滚动假死

### ISSUE THREAD

**Issue by zZ-wWw** [fluttercandies/extended_nested_scroll_view#27]
你好，我在使用了 extended_nested_scroll_view 的 pinnedHeaderSliverHeightBuilder 之后，
在某些机型(iphone6，应该跟列表的可视高度有关)上，当列表的的滚动高度在某个范围内，滚动时，列表会发生假死（NestedScrollView 再没有响应)

这是我的项目地址：https://github.com/zZ-wWw/flutter_app
我的Flutter版本：

> $ flutter doctor
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[!] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.42.1)
[✓] Connected device (1 available)

**Comment by zmtzawqlp** [comment]
1.弄清楚pinnedHeaderSliverHeightBuilder的意义
2.说需求，看代码根本不知道你要做什么

**Comment by zZ-wWw** [comment]
当我设置了pinnedHeaderSliverHeightBuilder后，在某种情况下（列表的滚动区域在指定的高度范围内），会导致列表无法滚动，NestedScrollView也无法再响应任何的手势事件，具体表现如下：
![bugs](https://user-images.githubusercontent.com/22167176/77274588-37f5df80-6cf1-11ea-9bd6-421eb6986c1e.gif)
![bugs1](https://user-images.githubusercontent.com/22167176/77274599-3debc080-6cf1-11ea-829c-48d7f48578c5.gif)

**Comment by zmtzawqlp** [comment]
1.好好看一下文档，设置下Example for issue 2
