### ISSUE TITLE
列表开启切换缓存时的bug

### ISSUE THREAD

**Issue by Gentear** [fluttercandies/extended_nested_scroll_view#3]
TabBarView开启切换缓存时，tab1上划，切换到tab0下划，然后切换到tab1，tab1列表内容仍为之前滑到的位置

**Comment by zmtzawqlp** [comment]
@Gentear 请使用官方默认的，这个组件就是解决。。tabbarview 缓存之后。。滚动列表。列表都会互相影响。。

**Comment by zmtzawqlp** [comment]
如果。你不要保存列表状态，请使用官方默认
