### ISSUE TITLE
pull to refresh not working on ios

### ISSUE THREAD

**Issue by fauzi2107** [fluttercandies/extended_nested_scroll_view#31]
Hi, thanks for the plugin, i tried to implement this plugin on my apps,
its working on Android but not on iOS

<img width="440" alt="Screen Shot 2020-05-28 at 19 07 57" src="https://user-images.githubusercontent.com/34369203/83139471-a3579580-a116-11ea-8d45-98dd59ec1a3e.png">

that is how i implement NestedScrollViewRefreshIndicator on my App

**Comment by zmtzawqlp** [comment]
may be you can try https://github.com/fluttercandies/pull_to_refresh_notification , i can't download your srceen shot 
![image](https://user-images.githubusercontent.com/16477333/83232270-7a3f0f80-a1bf-11ea-894b-5699bc38a327.png)
