### ISSUE TITLE
Scrolling  up the list in second tab brings back the listview in first tab to the top

### ISSUE THREAD

**Issue by rvamsikrishna** [fluttercandies/extended_nested_scroll_view#33]
If you scroll to item 25 in first tab, then scroll to some item in second tab, everything works fine. But as soon as you scroll a little bit up in second tab and go back to first tab, the list is returned to zero instead of staying at item 25.

**Comment by zmtzawqlp** [comment]
if you scroll all of body and start to scroll head every list will reset to zero

**Comment by rvamsikrishna** [comment]
Can we prevent this behavior? The list in the first tab should not move to the top on small scroll in second tab.

**Comment by renrael-yzal** [comment]
> Can we prevent this behavior? The list in the first tab should not move to the top on small scroll in second tab.

are you able to solve this problem?
