### ISSUE TITLE
Reversed ListView inside NestedScrollView

### ISSUE THREAD

**Issue by luccascorrea** [fluttercandies/extended_nested_scroll_view#37]
Hi,
First of all, thanks for the great lib! It fixes some annoying issues with NestedScrollView.

One issue that it didn't fix though is this one: https://github.com/flutter/flutter/issues/39134

This issue happens when you add a reversed ListView to a NestedScrollView. 
Would you have any guesses on how this could be solved? I don't understand the inner workings of the NestedScrollView implementation so I thought someone here might be able to help.

Thanks a lot

Luccas

**Comment by zmtzawqlp** [comment]
NestedScrollView  has two scrollcontrol, i think you should reverse data better

**Comment by brianschardt** [comment]
@zmtzawqlp this is the issue i am running into as well. great library btw. Im looking into a solution now

**Comment by zmtzawqlp** [comment]
seem issue has closed by flutter team， reopen this issue if need
