### ISSUE TITLE
更新了最新flutter 的sdk后，编译不通过

### ISSUE THREAD

**Issue by hoopslb** [fluttercandies/extended_nested_scroll_view#4]
Flutter 1.7.4-pre.105 • channel master
Dart 2.4.0

error：

Compiler message:                                                       
file:///Users/lee/tools/flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_nested_scroll_view-0.3.5/lib/src/nested_scroll_view_refresh_indicator.dart:363:24: Error: The argument type 'String' can't be assigned to the parameter type 'DiagnosticsNode'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///Users/lee/tools/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'DiagnosticsNode'.
              context: 'when calling onRefresh',                        
                       ^                                                
Compiler terminated unexpectedly. 
--------------------------------------------

这么传参可以通过
context: DiagnosticsNode.message('when calling onRefresh'),

**Comment by zmtzawqlp** [comment]
以stable版本为主，新的flutter 版本，老是改api。

**Comment by zmtzawqlp** [comment]
```dart
  extended_nested_scroll_view:
    git:
      url: https://github.com/fluttercandies/extended_nested_scroll_view.git
      ref: dev
```
link it as this,  i will update codes to pub later

**Comment by zmtzawqlp** [comment]
base on v1.7.8 is ready in pub, please update it.
