### ISSUE TITLE
tabview滚动问题。

### ISSUE THREAD

**Issue by 343629302** [fluttercandies/extended_nested_scroll_view#41]
当使用AutomaticKeepAliveClientMixin 。现在有tabview1 和 tabview2  。当tabview1的滚动吸顶，当切换到tabview2的时候取消滚动吸顶。但是因为tabview1的状态是被记录了还是属于滚动了一部分状态。这个问题怎么解决？

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_nested_scroll_view/issues/40
