### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by syssam** [fluttercandies/extended_nested_scroll_view#49]
Please check https://github.com/flutter/flutter/issues/66250

**Comment by zmtzawqlp** [comment]
we don't support null able util official stable release.

**Comment by syssam** [comment]
note, please plan to support before the stable release.

**Comment by lyf571321556** [comment]
same error！

**Comment by aguanteyo2** [comment]
Same error. Any news yet?

**Comment by Akiat** [comment]
Does anyone have a solution for this?

**Comment by zmtzawqlp** [comment]
i will create dev branch for flutter master later

**Comment by yasinarik** [comment]
Is this something similar: #53? I am in an urgent situation, do you have any solutions? Thanks a lot!!!

@zmtzawqlp  @Akiat @aguanteyo2 @lyf571321556 @syssam

**Comment by Akiat** [comment]
Sorry @yasinarik, on my side I'm just waiting for the fix :/

**Comment by yasinarik** [comment]
> Sorry @yasinarik, on my side I'm just waiting for the fix :/


https://github.com/flutter/flutter/issues/40740#issuecomment-735221208

Have a look at this please. I changed Flutter channel to stable from beta. Stable channel doesn't use the null safety yet. 

It works for now but a PR for the package is surely needed.

**Comment by Akiat** [comment]
Yes, to fix this, the stable channel of flutter, which doesn't use the null safety, works like a charm. But in my case, the master branch is needed :)

**Comment by zmtzawqlp** [comment]
2.0.0-dev is ready on pub.dev

**Comment by aaesDev** [comment]
hey, at first i used 2.0.0-dev and i didn't get any errors but then after two days i started to get the same errors again.

**Comment by bananagag** [comment]
Is it now time to migrate to null safety?

**Comment by zmtzawqlp** [comment]
3.0.0 support null-safety
