### ISSUE TITLE
滚动操作无法传递到 body

### ISSUE THREAD

**Issue by seasonyuu** [fluttercandies/extended_nested_scroll_view#5]
在 `extended.NestedScrollView` 中设置了 `controller` 之后，调用 `controller.jumpTo(offset)`，如果 `offset` 超过了 `headerSliverBuilder` 定义的 `expandedHeight`，则只会滚动到 `expandedHeight`，不会继续去操作 body 中的滚动。

且由于你的库中，对 body 中的控件设置了 `controller`，外部也已经不能再设置别的 `controller` 来进行控制了。

**Comment by zmtzawqlp** [comment]
这是官方代码。。我只是解决三个问题。。你也可以控制body里面的control。办法。我在群里讲过
![image](https://user-images.githubusercontent.com/16477333/60270185-6ee5c300-9922-11e9-8e04-524a7581c014.png)

**Comment by zmtzawqlp** [comment]
加群我让小伙伴告诉你做法
