### ISSUE TITLE
当我使用NestedScrollView 在其body里面使用 PrimaryScrollController primaryScrollController =  context.ancestorWidgetOfExactType(typeOf<PrimaryScrollController>());       _innerC = primaryScrollController.controller;让头部和body同步联动起来，当页面移除 摧毁时 会报这个错误 

### ISSUE THREAD

**Issue by mht-cpu** [fluttercandies/extended_nested_scroll_view#52]

**Comment by mht-cpu** [comment]
The following assertion was thrown while finalizing the widget tree:
I/flutter (27581): A _NestedScrollController was used after being disposed.
I/flutter (27581): Once you have called dispose() on a _NestedScrollController, it can no longer be used.
I/flutter (27581):
I/flutter (27581): When the exception was thrown, this was the stack:
I/flutter (27581): #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:108:9) 
I/flutter (27581): #1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:114:6)
I/flutter (27581): #2      ChangeNotifier.dispose (package:flutter/src/foundation/change_notifier.dart:181:12)
I/flutter (27581): #3      ScrollController.dispose (package:flutter/src/widgets/scroll_controller.dart:205:11)
I/flutter (27581): #4      _NestedScrollCoordinator.dispose (package:extended_nested_scroll_view/src/old_extended_nested_scroll_view.dart:1002:22)
I/flutter (27581): #5      NestedScrollViewState.dispose (package:extended_nested_scroll_view/src/old_extended_nested_scroll_view.dart:380:18)

**Comment by zmtzawqlp** [comment]
建议给官方提一个issue

**Comment by virskor** [comment]
我也遇到了
