### ISSUE TITLE
Update documentation on the 2.0.0 breaking changes

### ISSUE THREAD

**Issue by nnkti18** [fluttercandies/extended_nested_scroll_view#56]
I noticed that the library was upgraded to 2.0.0 version a couple of days ago. This update introducing 2 breaking changes but I can't find any information about them. Can you update it in the document?

**Comment by zmtzawqlp** [comment]
Breaking change: add clipBehavior and restorationId   flutter: ">=1.22.4"

**Comment by zmtzawqlp** [comment]
please read changelog

**Comment by nnkti18** [comment]
> Breaking change: add clipBehavior and restorationId flutter: ">=1.22.4"

I mean that the docs should add what is restorationId and its usage.

**Comment by zmtzawqlp** [comment]
official property from  flutter sdk

**Comment by nnkti18** [comment]
> official property from flutter sdk

Thanks. I appreciate your support.
