### ISSUE TITLE
执行demo报错！'activity.isScrolling': is not true!

### ISSUE THREAD

**Issue by weiweilidd01** [fluttercandies/extended_nested_scroll_view#57]
[
![QQ20201215-0](https://user-images.githubusercontent.com/44386932/102203355-724c8000-3f03-11eb-8965-a70f45b4366b.png)
](url)

运行环境： flutter为当前最新版本

**Comment by zmtzawqlp** [comment]
2.0.0-dev for flutter master branch

**Comment by MSoftwareSolutions** [comment]
Also getting activity.isScrolling is not true! with latest package version 2.0.0 and flutter version 1.22.5

**Comment by zmtzawqlp** [comment]
please provide demo

**Comment by aggeloskoutanis** [comment]
I have the same issue with flutter 3.7.10.

**Comment by ayyoub-coder** [comment]
@zmtzawqlp  I encountered this issue when trying to scroll from the top of the page, specifically from the sliver header, not from the list. To resolve this, I wrapped the body with ExtendedVisibilityDetector  

> please provide demo
