### ISSUE TITLE
bug: pointerScroll方法没有实现

### ISSUE THREAD

**Issue by Leadrive** [fluttercandies/extended_nested_scroll_view#59]
old_extended_nested_scroll_view.dart
中的_NestedScrollPosition没有实现父类的
void pointerScroll(double delta);

**Comment by Leadrive** [comment]
有可能是pub.flutter-io.cn中的代码不对，我看github的代码是注释了这句。

**Comment by zmtzawqlp** [comment]
你可以用dev的，这个api 后面才加的

**Comment by zmtzawqlp** [comment]
2.0.0-dev
