### ISSUE TITLE
Whis is the difference between old and new one?

### ISSUE THREAD

**Issue by KingWu** [fluttercandies/extended_nested_scroll_view#6]
I found your example has some commented code. These code is using a new approach but commented. What is the difference?

**Comment by zmtzawqlp** [comment]
New ExtendedNestedScrollView still has some issues in special layout, make it as obsolete for now till find a better solution

**Comment by KingWu** [comment]
I see.  Your plugin will have new release soon?

**Comment by zmtzawqlp** [comment]
if find a better way to figure out current tab
