### ISSUE TITLE
adding ScrollViewKeyboardDismissBehavior enum

### ISSUE THREAD

**Issue by brianschardt** [fluttercandies/extended_nested_scroll_view#60]
adding ScrollViewKeyboardDismissBehavior enum
Would be awesome

https://api.flutter.dev/flutter/widgets/ScrollViewKeyboardDismissBehavior-class.html

**Comment by zmtzawqlp** [comment]
i will include it in next version

**Comment by zmtzawqlp** [comment]
3.0.0
