### ISSUE TITLE
compile on beta lastest version post a error

### ISSUE THREAD

**Issue by lyf571321556** [fluttercandies/extended_nested_scroll_view#61]
../../.pub-cache/hosted/pub.flutter-io.cn/extended_nested_scroll_view-0.4.0/lib/src/old_extended_nested_scroll_view.dart:1069:7: Error: The non-abstract class '_NestedScrollPosition' is missing implementations for these members:
- ScrollPosition.pointerScroll
flutter doctor -v:
[✓] Flutter (Channel beta, 1.26.0-17.6.pre, on Mac OS X 10.15.5 19F101 darwin-x64, locale zh-Hans-CN)
    • Flutter version 1.26.0-17.6.pre at /Users/liuyanfeng/Library/flutter
    • Framework revision a29104a69b (3 days ago), 2021-02-16 09:26:56 -0800
    • Engine revision 21fa8bb99e
    • Dart version 2.12.0 (build 2.12.0-259.12.beta)
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

**Comment by zmtzawqlp** [comment]
try 2.0.1-dev

**Comment by MoacirSchmidt** [comment]
2.0.1-dev solved this problemas for me. Thank you very much
