### ISSUE TITLE
The non-abstract class '_NestedScrollPosition' is missing implementations for these members:  - ScrollPosition.pointerScroll

### ISSUE THREAD

**Issue by naamapps** [fluttercandies/extended_nested_scroll_view#63]
On Flutter 2.0, I get this error when trying to build the app.
I use version 2.0.1 of this package - the latest version.
```
../../../../flutter/.pub-cache/hosted/pub.dartlang.org/extended_nested_scroll_view-2.0.1/lib/src/old_extended_nested_scroll_view.dart:1229:7: Error: The non-abstract class '_NestedScrollPosition' is missing implementations for these members:
 - ScrollPosition.pointerScroll                                         
Try to either                                                           
 - provide an implementation,                                           
 - inherit an implementation from a superclass or mixin,                
 - mark the class as abstract, or                                       
 - provide a 'noSuchMethod' implementation.                             
                                                                        
class _NestedScrollPosition extends ScrollPosition                      
      ^^^^^^^^^^^^^^^^^^^^^                                             
../../../../flutter/packages/flutter/lib/src/widgets/scroll_position.dart:777:8: Context: 'ScrollPosition.pointerScroll' is defined here.
  void pointerScroll(double delta);           
```

Please help,
Thanks

**Comment by zmtzawqlp** [comment]
pls get 3.0.0

**Comment by yasinarik** [comment]
> pls get 3.0.0

Version 3.0.0 is for null safety but **we can't convert** to null-safety yet. 

Version `extended_nested_scroll_view: ^1.0.1` was working before but it doesn't any more :/

### Error Code
```
../../../.pub-cache/hosted/pub.dartlang.org/extended_nested_scroll_view-2.0.1/lib/src/old_extended_nested_scroll_view.dart:1229:7: Error: The non-abstract class '_NestedScrollPosition' is missing implementations for these members:
 - ScrollPosition.pointerScroll
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class _NestedScrollPosition extends ScrollPosition
      ^^^^^^^^^^^^^^^^^^^^^
../../../fvm/versions/1.25.0-4.0.pre/packages/flutter/lib/src/widgets/scroll_position.dart:778:8: Context: 'ScrollPosition.pointerScroll' is defined here.
  void pointerScroll(double delta);
       ^^^^^^^^^^^^^
```


I have tried all of them:

- 3.0.0
- 2.0.1-dev
- 2.0.1
- 2.0.0
- 1.0.1

### What can you do for solving it? Thank you very much!

**Comment by naamapps** [comment]
@yasinarik you don't have to be full null safety.
You can be unsound null safety, so your code can be non null safe, but packages can be null safe and it will work properly.

**Comment by yasinarik** [comment]
@naamapps Hey thanks for the reply! I am currently using `Flutter 1.25.0-4.0.pre`. Because of that I cannot upgrade the package at the moment.

I have checked if all the packages we have in our project support `null safety` and yes, they do. I am going to upgrade the SDK first. After the upgrade I will try the `3.0.0`version of Extended Nested Scroll View.

**Comment by naamapps** [comment]
@yasinarik no problem!
Just so you know, you can upgrade the flutter version and nothing really happens until you change Dart sdk version.
I'm also not on null safety yet but on flutter 2.0.4 and Dart 2.11 (null safety is on 2.12) and everything works fine - some packages are on null safety and others not yet.

**Comment by yasinarik** [comment]
@naamapps hmm.. So how can I use the 3.0.0 version of this package without upgrading nor migrating to null safety?

I get errors. Just couldn't figure it out. 🙄🤔

(BTW, although seeing those numbers is upsetting the covid app you made is very good. Congrats on that.)

**Comment by naamapps** [comment]
@yasinarik, if you prefer sticking with flutter 1.25 it's also fine, but it is possible. Search unsound null safety on Google.

And thanks a lot! I made the covid app just for the experience. Glad you liked it.
