### ISSUE TITLE
NestedScrollViewRefreshIndicator removed?

### ISSUE THREAD

**Issue by SeongBrave** [fluttercandies/extended_nested_scroll_view#64]
NestedScrollViewRefreshIndicator removed

**Comment by rubenvereecken** [comment]
For anyone else with this problem, you can find `PullToRefreshNotification` in another package, see the example:

https://github.com/fluttercandies/extended_nested_scroll_view/blob/6649c70bcaa6c2068d6e7ae4510d5779c1b2b68a/example/pubspec.yaml#L29
