### ISSUE TITLE
VIVO手机 pull to refresh页面， 向下滑动两个TAB后再向上滑动, 此时切换TAB，滚动条位置被重置

### ISSUE THREAD

**Issue by bill-9527-sc** [fluttercandies/extended_nested_scroll_view#65]
测试手机： VIVO IQOO3
Flutter版本：2.0.1
问题及复现步骤：
1. 进入pull to refresh页面，分别向下滑动TAB0, TAB1，此时TAB0,TAB1的滚动条位置可以正常记录
2. 向上滑动TAB0（或TAB1），之后切换TAB，发现滚动条被重置，再切换回原TAB，滚动条也被重置
3. 使用PC端Chrome浏览器测试运行，未发现此问题

**Comment by zmtzawqlp** [comment]
试试最新的版本
