### ISSUE TITLE
NeverScrollableScrollPhysics无法禁止滚动

### ISSUE THREAD

**Issue by wengxianxun** [fluttercandies/extended_nested_scroll_view#66]
physics: const NeverScrollableScrollPhysics(),

**Comment by zmtzawqlp** [comment]
你是不是body里面设置了scrollcotnrol

**Comment by Hynsen** [comment]
这似乎不适body里设置的scrollcontroller影响，因为body仅仅只放一个container，physics依然无效

**Comment by czeras** [comment]
@wengxianxun 请教一下你这个问题怎么解决的？我现在也遇到这个问题了

**Comment by devyu** [comment]
> @wengxianxun 请教一下你这个问题怎么解决的？我现在也遇到这个问题了

@czeras 请问你解决了吗？怎么解决的？

**Comment by czeras** [comment]
没解决,给产品说暂时解决不了



在 2023-12-21 23:50:06，"Whale" ***@***.***> 写道：

@wengxianxun 请教一下你这个问题怎么解决的？我现在也遇到这个问题了

@czeras 请问你解决了吗？怎么解决的？
