### ISSUE TITLE
向上拉动态更新数据之后再向下滑动列表过程中报这个异常，但是程序没有奔溃，不知道是怎么回事

### ISSUE THREAD

**Issue by guchengxi1994** [fluttercandies/extended_nested_scroll_view#69]
`Another exception was thrown: 'package:extended_nested_scroll_view/src/old_extended_nested_scroll_view.dart': Failed assertion: line 1640 pos 9: 'result': is not true.`

**Comment by purestart** [comment]
同问，一样的，我也经常报这个错，  有时候还会崩溃，遇到崩溃吗，滑动快的时候 或者突然滑到底

**Comment by guchengxi1994** [comment]
我用模拟器运行没有遇到奔溃的情况，真机还没大规模测试过，如果真的像你说的会奔溃的话可能要换别的方案才行了。

**Comment by zmtzawqlp** [comment]
请提供，最小的能重现问题的demo，以及环境条件

**Comment by zmtzawqlp** [comment]
没有重现过，请使用最新的版本试试
