### ISSUE TITLE
How to make TabBar pin at the top?

### ISSUE THREAD

**Issue by KingWu** [fluttercandies/extended_nested_scroll_view#7]
Previously, i use SliverPersistentHeader for Pinned header.

But, for your example, you don't use SliverPersistentHeader. So, how do you do that?

**Comment by zmtzawqlp** [comment]
SliverPersistentHeader  is the same , and it's include in  pinned header height

**Comment by KingWu** [comment]
````
//  widgets.add(SliverPersistentHeader(
//      pinned: true,
//      floating: false,
//      delegate: CommonSliverPersistentHeaderDelegate(
//          Container(
//            child: primaryTabBar,
//            //color: Colors.white,
//          ),
//          primaryTabBar.preferredSize.height)));
````

But, i found these codes are commented.  You mean extended.NestScrollView is handled the pinned header internally?

**Comment by zmtzawqlp** [comment]
right.you can use SliverPersistentHeader , and remember set pinnedHeaderHeight.

**Comment by KingWu** [comment]
@zmtzawqlp 
I am facing the rollback issue. 
https://vimeo.com/345854436

Widget Tree for Demo page
````
NestedScrollView
  SilverAppBar
    Column
       TabBar
       TabView
````

Widget Tree for each TabView
````
ListView
      HeaderContent
      Card
      Card
      Card
````
Does i implement in a wrong way?

**Comment by zmtzawqlp** [comment]
put this
![image](https://user-images.githubusercontent.com/16477333/60572501-52290f80-9da8-11e9-85fd-da04bd25ec03.png) in nestedscrollview body.

please tell the problem, and provide demo
