### ISSUE TITLE
当tab前面的内容超过一屏，或者说超过一屏更多，下面的内容在没有吸顶的情况下，listview跟着滑动

### ISSUE THREAD

**Issue by cqkyis** [fluttercandies/extended_nested_scroll_view#74]
测试大佬的demo，也会出现类同的情况，希望大佬能指点一下，。情况台下，
`body: extended.NestedScrollView(
        headerSliverBuilder: (context, f) {
          return [
            ExtendedSliverAppbar(
              title: IndexTitle(),
              leading: Container(),
              isOpacityFadeWithTitle: false,
              isOpacityFadeWithToolbar: false,
              background: IndexBackgroud(),
            ),
            SliverPersistentHeader(
              delegate: BaseSliverPersistentHeader(
                child: buidTabBar(),
                maxHeight: 50,
                minHeight: 50,
              ),
              pinned: true,
            ),
          ];
        },
        pinnedHeaderSliverHeightBuilder: () {
          return pinnedHeaderHeight;
        },
        body: TabBarView(
          controller: homeController.tabController,
          children: homeController.pageList,
        ),
      ),
    );`

**Comment by zmtzawqlp** [comment]
官方的会吗

**Comment by cqkyis** [comment]
已解决，官方的也有这个问题

**Comment by zmtzawqlp** [comment]
你可以试着pr ，我看看

**Comment by cqkyis** [comment]
old那个dart的1032行，if(innerDate <=-1 && innerDart >=1 )解决的，不知道有没有问题

**Comment by zmtzawqlp** [comment]
有点取巧 而且为啥不写成 innerDate.abs() >=1.  其实之前我也写过，但是不是大于1.0，大于的一个常量，后来merge 方法代码，merge掉了

**Comment by zmtzawqlp** [comment]
///this is a bug that the out postion is not overscroll actually and it get minimal value
      ///do under code will scroll inner positions
      ///so i igore  minimal value here(value like following data)
      ///  I/flutter (14963): 5.684341886080802e-14
      /// I/flutter (14963): -5.684341886080802e-14
      /// I/flutter (14963): -5.684341886080802e-14
      /// I/flutter (14963): 5.684341886080802e-14
      /// I/flutter (14963): -5.684341886080802e-14
      /// I/flutter (14963): -5.684341886080802e-14
      /// I/flutter (14963): -5.684341886080802e-14
      if (innerDelta != 0.0 && innerDelta.abs() > 0.0001) {
        for (_NestedScrollPosition position in _currentInnerPositions) {
          position.applyFullDragUpdate(innerDelta);
        }
      }

**Comment by zmtzawqlp** [comment]
最新版本已经增加了判断0的优化
