### ISSUE TITLE
load more list 的demo有个问题，第一个tab内滚动到了中间位置，而第二个tab滚到了顶部，再拉会显示header，但是这时候切到第一个tab，拉动header后第一个tab内容会滑动，header则没反应

### ISSUE THREAD

**Issue by iBinbro** [fluttercandies/extended_nested_scroll_view#76]
load more list 的demo有个问题，第一个tab内滚动到了中间位置，而第二个tab滚到了顶部，再拉会显示header，但是这时候切到第一个tab，拉动header后第一个tab内容会滑动，header则没反应

预期效果：切回到第一个tab时，在第一个tab内拖动listview，listview相应滚动；在header拖动操作，整个列表相应滚动，而不是第一个tab里的listview相应滚动
现在的效果如图：
![IMG_3388](https://user-images.githubusercontent.com/15324447/124896030-ac03e600-e00f-11eb-9730-8037b234d9d3.GIF)

**Comment by zmtzawqlp** [comment]
as design, nested_scroll_view 的默认行为，你可以给官方提issue
