### ISSUE TITLE
列表同步滚动可以用pageview解决，只是你这个还是有问题。。。

### ISSUE THREAD

**Issue by YQjiuhao** [fluttercandies/extended_nested_scroll_view#8]
因为tabBarView是对pageView的封装，直接使用pageView，再在pageview子界面做界面缓存就不用那么麻烦！
只是滑动需要headerView那一段高度。。。

**Comment by zmtzawqlp** [comment]
那你是没有用nestedscrollview吧？

**Comment by zmtzawqlp** [comment]
解决的是官方nestedscorllview的问题

**Comment by YQjiuhao** [comment]
> 解决的是官方nestedscorllview的问题

嗯嗯，用你这个设置pinnedHeaderSliverHeightBuilder就能解决heiderView问题
