### ISSUE TITLE
设置 controller 后，如何获取滚动的 offset？

### ISSUE THREAD

**Issue by OHeroJ** [fluttercandies/extended_nested_scroll_view#81]
现在配置，只能监听到 header 部分的滚动。body 里面是其他 scroll, 他们的滚动就无法监测到了。 不知道有没有高招指点下。

现在自己的一个思路就是,   总偏移量 = header 的偏移量 + body 里面scroll 的偏移量。 但是这样做不灵活。

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_nested_scroll_view/blob/1f3965a6729a7a907162818a8e0586466836f398/example/lib/pages/complex/scroll_to_top.dart#L46

**Comment by zmtzawqlp** [comment]
_key.currentState.outerController and     _key.currentState.innerController

**Comment by zmtzawqlp** [comment]
你先看看demo 吧。。一般是不会自动去设置 controller 的
