### ISSUE TITLE
手势中断

### ISSUE THREAD

**Issue by flutting** [fluttercandies/extended_nested_scroll_view#84]
问题所在: demo->pull to refresh in header.
具体体现: 下拉刷新手势, 需要先将NestedScrollView下拉至顶部, 再次下拉, 才会触发.(即: 只要NestedScrollView向上拖动了, 那么第一次下拉手势, 只能将NestedScrollView滚动到顶部, 继续下拉则不会继续滚动, 只有松手后再次下拉, 才能触发下拉刷新.)

**Comment by krmao** [comment]
@flutting 帅哥后来解决了没？

**Comment by flutting** [comment]
> @flutting 帅哥后来解决了没？

没.
