### ISSUE TITLE
show/hide SliverAppBar when scrolling ListView without having to wait for top index position of ListView

### ISSUE THREAD

**Issue by anasmano** [fluttercandies/extended_nested_scroll_view#85]
Hello,

I am having SliverAppbar in header, and ListView in body.
my question is: can i show/hide my SliverAppBar when scrolling ListView without having to wait for top index position of ListView. 
Because currently behavior of the  extended_nested_scroll_view library is  always just to scroll till top of listview to show/hide AppBar,

Thank You.

**Comment by zmtzawqlp** [comment]
The question is not refer to extended_nested_scroll_view, it's default behavior of SliverAppBar
