### ISSUE TITLE
Tabs sync issue is not solved in versions 4.0 and 5.0

### ISSUE THREAD

**Issue by naamapps** [fluttercandies/extended_nested_scroll_view#89]
Hey,
In versions before 4.0, the sync issue was fixed, but with the refractor in 4.0 something is not working there. 
I set `onlyOneScrollInBody` to true but the tabs still scrolls together sometimes.
Even in the simple example in the demo website, you will find the sync bug there. 
Please help, 
Thanks.

**Comment by zmtzawqlp** [comment]
please provide runnable demo, i can't reproduce at my side

**Comment by naamapps** [comment]
Hey @zmtzawqlp,
Here is a video of the issue,
As you can see, there are 2 issues:
1. When the second tab have a shorter list, and scrolling a little bit, the first tab also scrolls (sync issue - 00:07 in the video).
2. At 00:42 in the video, you can see the header showed a bit even when we are not at the top of the first tabs list. This happens because the **list in the second tab is at the top** so the sync issue is not solved and it thinks that the header needs to show. 

All this issues were not present in versions before 4.0.
Unfortunately I can't share the code as its private.
But I promise you it is like in the example.

Also sometimes I get this error:
```
══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown while notifying listeners for AnimationController:
'package:extended_nested_scroll_view/src/extended_nested_scroll_view.dart': Failed assertion: line
1740 pos 9: 'result': is not true.

When the exception was thrown, this was the stack:
#2      _NestedOuterBallisticScrollActivity.applyMoveTo (package:extended_nested_scroll_view/src/extended_nested_scroll_view.dart:1740:9)
#3      BallisticScrollActivity._tick (package:flutter/src/widgets/scroll_activity.dart:553:10)
```

https://user-images.githubusercontent.com/37176893/133048051-0bbc4bfe-b481-4210-a1e5-557658f07295.mp4

**Comment by hylsabella** [comment]
> Hey,
> In versions before 4.0, the sync issue was fixed, but with the refractor in 4.0 something is not working there.
> I set `onlyOneScrollInBody` to true but the tabs still scrolls together sometimes.
> Even in the simple example in the demo website, you will find the sync bug there.
> Please help,
> Thanks.

https://github.com/fluttercandies/extended_nested_scroll_view/issues/82

**Comment by naamapps** [comment]
@zmtzawqlp please let me know if there's something we can do.. There is no purpose in using this package if the sync issue is not resolved.
Thanks

**Comment by zmtzawqlp** [comment]
@naamapps sorry, i can't reproduce at my side, please use old version if it is emergency for you. i will keep look into it.

**Comment by b3nni97** [comment]
Does not work for me either with the last master version

**Comment by hylsabella** [comment]
可以的话根据3.0.1版本重新搞一下吧，3.0.1版本后版本都有异常，谢谢

**Comment by zmtzawqlp** [comment]
please provide runnable simple demo and steps to reproduce this issue.

**Comment by hylsabella** [comment]
> 

demo代码和重现录屏之前已经提交过给你了，但是你之前说你那边不能重现，这个确实没办法，其他人也遇到类似问题，那应该是还有一些问题没解决

**Comment by andychan06** [comment]
你好 請問這個問題解決了沒有?

**Comment by hylsabella** [comment]
> 

3.0.1版本正常 #82

**Comment by hylsabella** [comment]
> 你好 請問這個問題解決了沒有?

3.0.1版本正常

**Comment by naamapps** [comment]
I don't understand what the others wrote, but from my side the problem is not solved.
Version 3 is perfect.
@zmtzawqlp I hope you can find the issue.

**Comment by zmtzawqlp** [comment]
> I don't understand what the others wrote, but from my side the problem is not solved. Version 3 is perfect. @zmtzawqlp I hope you can find the issue.

i can't reproduce at my side, i always wait someone can provide an simple runnable demo and clearly reproduce steps.
 you can use 3.0.0 version if it's emergency.

**Comment by zmtzawqlp** [comment]
> Hey, In versions before 4.0, the sync issue was fixed, but with the refractor in 4.0 something is not working there. I set `onlyOneScrollInBody` to true but the tabs still scrolls together sometimes. Even in the simple example in the demo website, you will find the sync bug there. Please help, Thanks.

webdemo is build in old version, i can't get what do you mean it didn't work.

**Comment by LeGoffMael** [comment]
I confirm that with latest version `5.0.0` the issue 2:tabview sync issue is not solved. Works well on version 3

**Comment by zmtzawqlp** [comment]
please try 5.1.2 version
* Provide ExtendedVisibilityDetector to point out which list is visible

**Comment by zmtzawqlp** [comment]
> @zmtzawqlp Can you please set the version of visibility_detector to be 0.3.3 (latest)? I can't upgrade because of version mismatch.

this is base on your sdk， it will 0.3.3 if you is in flutter 3.0.0

or you can override 

dependency_overrides:
  visibility_detector: ^0.3.3

**Comment by zmtzawqlp** [comment]
i use 0.22 , so more people can use [extended_nested_scroll_view](https://github.com/fluttercandies/extended_nested_scroll_view)

**Comment by sed1ka** [comment]
based on [dart: depedencies](https://dart.dev/tools/pub/dependencies), they warn about using dependencies_override

> Warning: Using a dependency override involves some risk. For example, using an override to specify a version outside the range that the package claims to support, or using an override to specify a local copy of a package that has unexpected behaviors, may break your application.

I agree with @naamapps
I think forcing the user to update the latest version of visibility_detector is not bad thing, than the risk that might occur when using dependencies_override. After all, one day we will have to use the latest version of the library (which has a lot of fixes and enhancements)

**Comment by zmtzawqlp** [comment]
close with https://github.com/fluttercandies/extended_nested_scroll_view/commit/029b0911cf3cfea57e8277e8a63429b26dc18aba

**Comment by renrael-yzal** [comment]
> please try 5.1.2 version
> 
> * Provide ExtendedVisibilityDetector to point out which list is visible

I have tried 5.1.2, but still issue is not fixed!
