### ISSUE TITLE
sliverappbar高度变化

### ISSUE THREAD

**Issue by xxssd-awsl** [fluttercandies/extended_nested_scroll_view#94]
kToolbarHeight=56    status top=32.72727272727272    custom tabs height=32
加起来就是120.72727272727272

使用NestedScrollView，收缩完毕后使用LayoutBuilder获取的flexibleSpace的biggest.height是120.72727272727272

使用ExtendedNestedScrollView，收缩完毕后使用LayoutBuilder获取的flexibleSpace的biggest.height是120.72727272727283

**Comment by j787701730** [comment]
这个误差好像会引起windows桌面端SliverAppBar的elevation失效(好像触发不了). 
```
final double pinnedHeaderHeight =
        //statusBar height
        statusBarHeight +
            //pinned SliverAppBar height in header
            kToolbarHeight -
            0.1;
```
减去0.1之后. elevation效果就出来了.  测试了安卓模拟器的减不减0.1, elevation都正常.

**Comment by zmtzawqlp** [comment]
double 精度问题
